[package]
name = "mandel_rayon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.0"
num-complex = "0.4.5"
rayon = "1.9.0"
